src/ColoursWeb/Pages/Account.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc.RazorPages;

using System.Threading.Tasks;

namespace ColoursWeb.Pages
{
    public class AccountModel : PageModel
    {
        public string AccessToken { get; set; }
        public async Task OnGet()
        {
            AccessToken = await HttpContext.GetTokenAsync("access_token");
        }
    }
}

src/ColoursWeb/Pages/Appinfo.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;

namespace ColourWeb.Pages
{
    public class ConfiginfoModel : PageModel
    {
        IConfiguration _config;
        public string strConfigHtml;

        public ConfiginfoModel(IConfiguration config)
        {
            _config = config;
            strConfigHtml = "";
        }
        public void OnGet()
        {
            strConfigHtml += "<ul>";
            strConfigHtml += "<li>Sistema Operativo: " + System.Runtime.InteropServices.RuntimeInformation.OSDescription + "</li>";
            strConfigHtml += "<li>Framework: " + System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription + "</li>";
            strConfigHtml += "<li>ASPNETCORE_ENVIRONMENT: " + _config.GetValue<string>("ASPNETCORE_ENVIRONMENT") + "</li>";
            strConfigHtml += "<li>InstrumentationKey: " + _config.GetValue<string>("ApplicationInsights:InstrumentationKey") + "</li>";
            strConfigHtml += "<li>BuildIdentifier: " + _config.GetValue<string>("BuildIdentifier") + "</li>";
            strConfigHtml += "</ul>";
        }
    }
}

src/ColoursWeb/Pages/Config.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;

namespace ColourWeb.Pages
{
    public class ConfigModel : PageModel
    {
        [BindProperty]
        public string APIUrl { get; set; }
        [BindProperty]
        public bool APIMode { get; set; }

        public void OnGet()
        {
            var vURL = Request.Cookies["APIUrl"];
            if (vURL != null) {
                APIUrl = vURL.ToString();
                APIMode = (Request.Cookies["APIMode"] == "Direct") ;
            }
            else
            {
                APIUrl = "https://coloursapi.app.aprender.it/colours/random";
                APIMode = true;
            }
                
        }

        public IActionResult OnPost()
        {
            if (APIUrl != null)
            {
                Response.Cookies.Append("APIUrl", APIUrl,
                    new CookieOptions
                    {
                        HttpOnly = false,
                        Secure = false,
                        Expires = DateTime.Now.AddMonths(12)
                    }
                );
                Response.Cookies.Append("APIMode", (APIMode) ? "Direct" : "" ,
                new CookieOptions
                {
                    HttpOnly = false,
                    Secure = false,
                    Expires = DateTime.Now.AddMonths(12)
                }
              );
                return RedirectToPage("/Index");
            }

            return RedirectToPage("/Config");
        }

    }
}

src/ColoursWeb/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ColoursWeb.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

src/ColoursWeb/Pages/GetColour.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;
using System.Net.Http;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.AspNetCore.Mvc.Infrastructure;

namespace ColoursWeb.Pages
{
    public class ColoursItem
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Data { get; set; }

    }


    public class GetColourModel : PageModel
    {
        public string strResponse;
        public int iStatusCode = 200;

        public static async Task<string> OnGetPink()
        {
            string[] strColors = { "pink", "hotpink", "deeppink", "fuchsia", "mediumvioletred" };
            Random r = new Random();
            int rInt = r.Next(strColors.Length);

            ColoursItem _Item = new ColoursItem()
            {
                Id = 1,
                Name = strColors[rInt],
                Data = ""
            };

            await Task.Run(() => { });

            return JsonSerializer.Serialize(_Item, new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase, WriteIndented = true });

        }

        public static async Task<string> OnGetRelay(string vURL)
        {

            await Task.Run(() => { });

            try
            {
                HttpClient client = new HttpClient();

                var msg = client.GetStringAsync(vURL).Result;

                return msg;
            }
            catch (Exception ex)
            {
                ProblemDetails res = new ProblemDetails { Status = 500, Title = ex.Message };

                return res.ToString();
            }

        }

        public async Task OnGetAsync()
        {
            var vURL = Request.Cookies["APIUrl"];

            if (vURL == "pink")
            {
                strResponse = await OnGetPink();
            }
            else
            {
                try
                {
                    HttpClient client = new HttpClient();
                    strResponse = client.GetStringAsync(vURL).Result;

                }
                catch (Exception ex)
                {
                    iStatusCode = 500;
                    ProblemDetails res = new ProblemDetails { Status = 500, Title = ex.Message };
                    strResponse = JsonSerializer.Serialize(res, new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase, WriteIndented = true });
                }
            }
        }
    }

}

src/ColoursWeb/Pages/Index.cshtml.cs
using ColoursWeb;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.RazorPages;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text.Json;
using System.Threading.Tasks;

namespace ColourWeb.Pages
{
    public class IndexModel : PageModel
    {

        public string Api { get; set; }
        public bool Direct { get; set; }
        List<ColoursItem2> ColorsList { get; set; } = new List<ColoursItem2>();
        public string Colors { get; set; } = "";

        private readonly HttpClient _httpClient;

        public IndexModel(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        public void OnGet()
        {
            var api = Request.Cookies.FirstOrDefault(x => x.Key == "APIUrl");

            if (api.Value is not null)
            {
                Api = api.Value;
            }
            else
            {
                Api = "https://coloursapi.app.aprender.it/colours/random";
            }

            Response.Cookies.Append("APIUrl", Api);

            var mode = Request.Cookies.FirstOrDefault(x => x.Key == "APIMode");

            if (mode.Value is not null)
            {
                Direct = mode.Value == "Direct";
            }

            Response.Cookies.Append("APIMode", Direct ? nameof(Direct): "");

        }
        // the click event handler 
        // MUST be prefixed with OnGet if the 
        // request is of HTTP GET type 
        public async Task OnGetOnClick()
        {
            var api = Request.Cookies.FirstOrDefault(x => x.Key == "APIUrl");
            Api = api.Value;

            var mode = Request.Cookies.FirstOrDefault(x => x.Key == "APIMode");

            if (mode.Value is not null)
            {
                Direct = mode.Value == "Direct";
            }

            for (int i = 0; i < 400; i++)
            {

                try
                {
                    var color = await _httpClient.GetFromJsonAsync<ColoursItem2>(api.Value);
                    ColorsList.Add(color);
                }
                catch (Exception)
                {
                    await Task.Delay(200);
                    var color = await _httpClient.GetFromJsonAsync<ColoursItem2>(api.Value);
                    ColorsList.Add(color);
                }
                

                

            }

            Colors = string.Join(",", ColorsList.Select(x => x.Data));


        }

    }
}

src/ColoursWeb/Pages/SingIn.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ColoursWeb.Pages
{
    public class SingInModel : PageModel
    {

        public IActionResult OnGet()
        {
            return Challenge(new AuthenticationProperties
            {
                RedirectUri = "/"
            });
        }
    }
}

src/ColoursWeb/Pages/SingOut.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ColoursWeb.Pages
{
    public class SingOutModel : PageModel
    {
        public IActionResult OnGet()
        {
            return SignOut("Cookies", "oidc");
        }
    }
}

src/ColoursWeb/Pages/Account.cshtml
@page
@model ColoursWeb.Pages.AccountModel
@{
}

<h3>Perfil</h3>

<table>
    <tr>
        <th>
            IsAuthenticated
        </th>
        <td>
            @User.Identity.IsAuthenticated
        </td>
    </tr>

</table>
<h5>Claims </h5>
<table class="table table-bordered table-striped">
    <tr>
        <th>
            Claim Type
        </th>
        <th>
            Claim Value
        </th>
        @*<th>
            Value Type
            </th>
            <th>
            Subject Name
            </th>
            <th>
            Issuer Name
            </th>*@
    </tr>
    @foreach (System.Security.Claims.Claim claim in User.Claims)
    {
        <tr>
            <td>
                @claim.Type
            </td>
            <td>
                @claim.Value
            </td>
            @*<td>
                @claim.ValueType
                </td>
                <td>
                @claim.Subject.Name
                </td>
                <td>
                @claim.Issuer
                </td>*@
        </tr>
    }
</table>


<h5>Access Token</h5>
<p>@Model.AccessToken</p>

src/ColoursWeb/Pages/Appinfo.cshtml
@page
@model ColourWeb.Pages.ConfiginfoModel
@{
    ViewData["Title"] = "Configinfo";
}

<h3>Info de esta Aplicación</h3>
<p> Esta aplicación fue desarrollada por <a href="https://aprender.it/">AprenderIT</a>, tomando como base la originalmente publicada por <a href="https://github.com/markharrison/Lab_APIM_Original">Mark Harrison</a>.</p>
<p>Su uso es exclusivo para fines educativos y forma parte del contenido de los <a href="https://aprender.it/cursos/">cursos publicados</a>.</p>
<p>Info adicional de contexto:</p>
@Html.Raw(Model.strConfigHtml)
<br />
<a href="/">Home</a>

src/ColoursWeb/Pages/Config.cshtml
@page
@model ColourWeb.Pages.ConfigModel
@{
    ViewData["Title"] = "Colour Config";
}

<div class="container-fluid">

    <h4>Configuraciones</h4>
    @using (Html.BeginForm())
    {
        <span>API URL:</span>
        <input size="50" asp-for="APIUrl" /><br /><br />
        <span>API Mode:</span>
        <input type="checkbox" asp-for="APIMode"  />  <span>&nbsp;Checkear para consumir desde el cliente (browser), sino será consumido mediante el front-end.</span>  <br /><br />
        <input type="submit" id="Submit" value="Submit">
    }

    <br /><br />

</div>

src/ColoursWeb/Pages/GetColour.cshtml
@page
@model ColoursWeb.Pages.GetColourModel
@{
    Layout = null;
    Response.ContentType = "application/json";
    Response.StatusCode = Model.iStatusCode;
}
@Html.Raw(Model.strResponse)

src/ColoursWeb/Pages/Index.cshtml
@page
@model ColourWeb.Pages.IndexModel
@{
    ViewData["Title"] = "Colour Home";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<div class="container-fluid">

    <p>Vamos a hacer un experimento con colores. Cada una de las bolas de más abajo se rellenará con un color cuando inicies el juego.</p>

    <hr style="border-top: 2px solid black" />

    <div id="idBalls"></div>

    <div style="margin-top: 10px;">
        @*@if (!Model.Direct)
        {
            <button class="btn btn-primary" id="idButStart" onclick="doStart(); return false;">Iniciar</button>
        }
        else
        {
            <a class="btn btn-primary" id="idButStart" asp-page="Index" asp-page-handler="OnClick"> Iniciar </a>
            <input type="hidden" id="colours" value=@Model.Colors />
        }*@
        <button class="btn btn-primary" id="idButStart" onclick="doStart(); return false;">Iniciar</button>
        <button class="btn btn-danger" id="idButReset" style="display:none;"  onclick="window.location.href='/'; return false;">Resetear</button>
    </div>

    <hr style="border-top: 2px solid black" />

    <p>Sobre el juego: &nbsp;&nbsp;<span id="idErrorText" style="color: red;"></span></p>
    <ul>
        <li>API: <span id="idAPIUrl"</span></li>
        <li>Detalles: cuando inicias el juego, se realizará una llamada a la API configurada para solicitar un color aleatorio. Si la operación es exitosa, se rellenará ese color en un lugar aleatorio del panel superior.</li>
    </ul>

</div>


@section scripts {


<script>
       var colours = document.getElementById('colours')?.value;
            console.log(colours)
    $(document).ready(function () {
        doDefaultReady();
    });
</script>
}

src/ColoursWeb/Pages/SingIn.cshtml
@page
@model ColoursWeb.Pages.SingInModel
@{
}

src/ColoursWeb/Pages/SingOut.cshtml
@page
@model ColoursWeb.Pages.SingOutModel
@{
}